### PR TITLE
examples: remove darwin SDKs from cross compile example

### LINKED ISSUE #320: Cannot find CoreFoundation
I have: 

```
          nativeBuildInputs = [pkg-config] ++
            lib.optionals stdenv.buildPlatform.isDarwin
              [libiconv darwin.apple_sdk.frameworks.Security darwin.apple_sdk.frameworks.CoreFoundation];
```

but on compile I get:

```
       >   = note: /nix/store/c9nh3pk0i63zymzb70pwm6d273dyicwn-aarch64-unknown-linux-gnu-binutils-2.40/bin/aarch64-unknown-linux-gnu-ld: cannot find /nix/store/6r8pwhq2pdfizknsd7m0sm4mi4a9aigr-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/CoreFoundation.framework/CoreFoundation: No such file or directory
```

Is there a way to fix this or should I not try to crosscompile frorm mac to `aarch64-linux`?

### PR DESCRIPTION
**Pull request by ipetkov**
## Motivation
Seems like these SDKs aren't necessary, and worse, they're causing issues for some reason. Might as well simplify the example a bit!

Fixes #320 

## Checklist

- [ ] added tests to verify new behavior
- [ ] added an example template or updated an existing one
- [ ] updated `docs/API.md` (or general documentation) with changes
- [ ] updated `CHANGELOG.md`

### CODE REVIEW

**Comment by alper** [comment]
Well, now I'm getting:

> = note: ld: framework not found Security
>           clang-11: error: linker command failed with exit code 1 (use -v to see invocation)

So removing that breaks it at a different point.

**Comment by alper** [comment]
But my research says that compiling from macOS to Linux is not supposed to work: https://users.rust-lang.org/t/cant-cross-compile-project-with-openssl/70922/6

**Comment by ipetkov** [comment]
Ah yeah its unfortunate that it basically doesn't work :(

**Comment by alper** [comment]
There are a bunch of different opinions on this. I'm chasing it for a while now but haven't seen it work yet. Not sure whether Nix provides a fully open source Linux compatible world to compile on macOS.

**Pull request merged**
