### PR TITLE
multi folder build support

### PR DESCRIPTION
**Pull request by dzmitry-lahoda**
## Motivation

```
./a/b/Cargo.toml - simple package without workspace
./c/d/Cargo.lock
./c/d/Cargo.toml - workspace
./c/d/e/Cargo.toml - package from workspace referencing ./a/b/Cargo.toml 
```

So we can setup toml file from any folder to allow non root folder build.

Are there other options?

## Checklist

- [ ] added tests to verify new behavior
- [ ] added an example template or updated an existing one
- [ ] updated `docs/API.md` with changes
- [ ] updated `CHANGELOG.md`

### CODE REVIEW

**Comment by ipetkov** [comment]
Thanks for the PR @dzmitry-lahoda! Could you elaborate a bit more on the project structure you are trying to build?

* Is there a single `flake.nix` file at the `./` root which builds all the crates together?
* Is the goal here to only build `./a/b/Cargo.toml`, or is the goal to build `./c/d/Cargo.toml` whose member has a path dependency on `./a/b/Cargo.toml`?
* Is `./a/b/Cargo.toml` a totally standalone project (i.e. does it also have a `Cargo.lock`)?

Although it is possible to allow `buildDepsOnly` to use an explicit path to a `Cargo.toml` file, it would still need to match with an appropriate `Cargo.lock` file (mixing and matching these from different workspaces _may_ work but it isn't guaranteed). Normally you'd want to pass the entire cargo workspace root to the Nix builder and then instruct cargo specifically which crates you'd want to build (e.g. by `cargo build -p mycrate`), but I'd like to understand a bit better about the concrete use-case and the troubles it is bringing!

**Comment by dzmitry-lahoda** [comment]
> Although it is possible to allow buildDepsOnly to use an explicit path to a Cargo.toml file, it would still need to match with an appropriate Cargo.lock file (mixing and matching these from different workspaces may work but it isn't guaranteed). Normally you'd want to pass the entire cargo workspace root to the Nix builder and then instruct cargo specifically which crates you'd want to build (e.g. by cargo build -p mycrate), but I'd like to understand a bit better about the concrete use-case and the troubles it is bringing!

I see. May be it would be issue. For now we build contracts. So it is not so big deal.

**Comment by dzmitry-lahoda** [comment]
https://github.com/ComposableFi/composable/blob/538d1c3df71083a2f38912627985683602eeaa39/cosmwasm/contracts/Cargo.lock <- contracts easy to build and small (so deps build only is not problem)

these depend on https://github.com/ComposableFi/composable/tree/538d1c3df71083a2f38912627985683602eeaa39/code/xcvm/lib/core

which is part of https://github.com/ComposableFi/composable/blob/538d1c3df71083a2f38912627985683602eeaa39/code/Cargo.lock (hard to build - we build deps - work well)

so we afraid moving `core` to separate folder not under workspace will be issue (moving to other git repo is issue too - hard to sync deps)

**Comment by ipetkov** [comment]
I see, the problem is that your workspace root itself is not an ancestor of all the crates it includes (so the Nix expression cannot just scope to a sub directory), and the workspace root is not part of the flake root either. In that case I'm open to merging this!

Are you interested in adding a simple test case to avoid any future regressions here? The crate contents can be empty, it's the structure that is interesting here

**Comment by dzmitry-lahoda** [comment]
1. examples of structure should be added
2. team decided to do reexport (pub use) of conflicting deps instead of split workspace (so it will bloat wasm files size and other not good things), so it is not prior for us not. so may be I will later return here when we will finally decide split (which is good IMHO)

**Comment by ipetkov** [comment]
Thanks again for the PR @dzmitry-lahoda ! I've ended up addressing this in #212 which was slightly different change which simplified these checks altogether

**Pull request closed without merging**
