### PR TITLE
fix(cargoDoc): Support cross-compilation of docs

### PR DESCRIPTION
**Pull request by x10an14**
## Checklist

- [ ] added tests to verify new behavior
- [ ] added an example template or updated an existing one
- [ ] updated `docs/API.md` (or general documentation) with changes
- [ ] updated `CHANGELOG.md`

### CODE REVIEW

**Comment by x10an14** [comment]
I don't consider this ready, but it's currently too late at night for me to manage to figure out how / where / which test (or test harness even) to copy/paste/piggy-back from.
Seems very involved (to me) for my level of (in)competence.

Nonetheless, thought I'd share the crucial fix, and hopefully start up a dialogue on how maybe to get this merged in =)

Kind Regards,
from someone very grateful for the awesome project! =DDD

**Comment by x10an14** [comment]
Found a fix for my situation:
```
commit d4005d610c2b583ce57ec67b9d5fb03c510ffb4c
Author: x10an14-nav <christian.chavez@nav.no>
Date:   Fri May 3 13:45:38 2024 +0200

    bugfix(flake): Fix cargo-doc derivation/nix check

diff --git a/flake.nix b/flake.nix
index e84cac7..a452dcc 100644
--- a/flake.nix
+++ b/flake.nix
@@ -61,11 +61,10 @@
         cargoArtifacts = craneLib.buildDepsOnly commonArgs;
 
         # Compile workspace code (including 3rd party dependencies)
-        cargo-doc = craneLib.cargoDoc (commonArgs // {inherit cargoArtifacts;});
         cargo-package = craneLib.buildPackage (commonArgs // {inherit cargoArtifacts;});
       in {
         checks = {
-          inherit cargo-package cargo-doc;
+          inherit cargo-package;
           # Run clippy (and deny all warnings) on the crate source,
           # again, resuing the dependency artifacts from above.
           #
@@ -79,14 +78,19 @@
               cargoClippyExtraArgs = "--all-targets -- --deny warnings";
             }
           );
-
+          cargo-doc = craneLib.cargoDoc (commonArgs
+            // {
+              inherit cargoArtifacts;
+              preInstall = ''
+                # TODO: Remove when/if https://github.com/ipetkov/crane/pull/603 gets accepted
+                ln -sT "''${CARGO_TARGET_DIR:-target}/''${CARGO_BUILD_TARGET:-}/doc" "''${CARGO_TARGET_DIR:-target}/doc"
+              '';
+            });
           cargo-fmt = craneLib.cargoFmt {inherit src;};
-
           cargo-audit = craneLib.cargoAudit {
             inherit (inputs) advisory-db;
             inherit src;
           };
-
           # Run tests with cargo-nextest
           # Consider setting `doCheck = false` on `cargo-package` if you do not want
           # the tests to run twice
```

**Comment by x10an14** [comment]
If anyone can think of a cleaner fix, feel free to share =)

**Review by ipetkov — APPROVED** [review]
Thanks for the PR @x10an14 ! I tweaked the implementation a bit to add a `docInstallRoot` attribute to allow more control for defining what it should be in case someone needs a bigger escape hatch

**Pull request merged**
