### PR TITLE
docs: typo lib.filterCargoSources -> craneLib.filterCargoSources

### PR DESCRIPTION
**Pull request by scvalex**
## Motivation

Typo in docs.  I tested by using this code locally.

## Checklist

- [ ] added tests to verify new behavior
- [ ] added an example template or updated an existing one
- [ ] updated `docs/API.md` (or general documentation) with changes
- [ ] updated `CHANGELOG.md`

### CODE REVIEW

**Review by ipetkov — APPROVED** [review]
Thanks for fixing this!

**Comment by ipetkov** [comment]
No idea why CI keeps failing, there's no way this MR has led to the failure

**Comment by scvalex** [comment]
CI's haunted.  That's the only explanation that makes sense.

**Comment by ipetkov** [comment]
Figured it out, will rerun these jobs once #328 is merged! (Cache will be freshly warmed too)

**Pull request merged**
